name: Playwright

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # Map GitHub Secrets to env vars used by your tests (.env not committed on CI)
      env:
      SAUCE_USER: ${{ secrets.SAUCE_USER }}
      SAUCE_PASS: ${{ secrets.SAUCE_PASS }}
      FIRST_NAME: ${{ secrets.FIRST_NAME }}
      LAST_NAME:  ${{ secrets.LAST_NAME }}
      ZIP:        ${{ secrets.ZIP }}
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers & deps
        run: npx playwright install --with-deps

      - name: Run tests (HTML report)
        run: npx playwright test --reporter=html

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test-results (traces/screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
